apiVersion: batch/v1
kind: Job
metadata:
  name: podacrobat-job
  namespace: kube-system
spec:
  template:
    metadata:
      name: podacrobat-job-pod
    spec:
      containers:
        - name: podacrobat
          image: stepdc/podacrobat:latest
          command:
            - "/app/podacrobat"
            - "--policy=podscount"
            - "--lowerthreshold=29"
            - "--upperthreshold=59"
      restartPolicy: "Never"
      serviceAccountName: podacrobat-sa
